### ISSUE TITLE
vim modelines

### ISSUE THREAD

**Issue by JohnathonNow** [JohnathonNow/wolfratbot#13]
I think most of the people who have contributed use vim, so it would be nice if each source file had a [vim modeline](http://vim.wikia.com/wiki/Modeline_magic) to aid in development for different users with different vim configurations.

**Comment by bdevorem** [comment]
Do you just want a modeline added to each file?

**Comment by bdevorem** [comment]
Any default configurations?

**Comment by JohnathonNow** [comment]
Yeah. I was thinking we'd want `expandtab`, `tabstop=4`, `shiftwidth=4`, and `softtabstop=4`.

**Comment by bdevorem** [comment]
Okay, just source files? Or every file?

**Comment by JohnathonNow** [comment]
Just source for now.
