### ISSUE TITLE
!wump n doesn't work

### ISSUE THREAD

**Issue by JohnathonNow** [JohnathonNow/wolfratbot#29]
but `!wumpn` does.

**Comment by JohnathonNow** [comment]
Also @a3qz how is `!wump s` supposed to work? When I do something like `!wumps 1 2 3` I get
```
  File "/Users/john/Source/wolfratbot/src/wrbcommands.py", line 120, in wump
    send.send(wumpus.ShootArrow(int(text[1:])))
TypeError: int() argument must be a string, a bytes-like object or a number, not 'list'
```

**Comment by a3qz** [comment]
Ah, not sure why i thought that would work
I think what it should be is ```send.send(wumpus.ShootArrow(map(lambda x: int(x), text[1:]))) ```

**Comment by bdevorem** [comment]
I can fix this @JohnathonNow

**Comment by JohnathonNow** [comment]
![image](https://user-images.githubusercontent.com/5497725/46493344-17c12080-c7de-11e8-95de-257f34847ef5.png)

**Comment by JohnathonNow** [comment]
Also wump should really be in its own module instead of in wrb commands.
